# Unités utilisées: [m], [kg]

Angles = [0,0,0,0]

[Barge]
Longueur = 0.55
Largeur = 0.6
Hauteur = 0.17
Masse = 9
Declage_grue = 0.15
ConstanteAmortissement = 0.7

[ContrePoids]
Masse = 1
# Pour sa longueur, il faut mettre la première articulation 
# à l'horizontale et mesurer ce qui dépasse à l'arrière de la grue
Longueur = 0.1

[Articulations]
0 = {longueur = 0.3, largeur = 0.08, masse = 0.5} #Socle
1 = {longueur = 0.3, largeur = 0.08, masse = 0.5}
2 = {longueur = 0.3, largeur = 0.08, masse = 0.5}
3 = {longueur = 0.1, largeur = 0.08, masse = 0.5}
4 = {longueur = 0.05, largeur = 0.1, masse = 0.2}